# -*- coding: utf-8 -*-
"""memory profiling TANS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PmfmCB2WS7cnZsIsR9ZDOXnXBEkbCaFX
"""

#%%
import numpy as np
from matplotlib import pyplot as plt


epoch = datetime.utcfromtimestamp(0)

def unix_time_millis(dt):
    return (dt - epoch).total_seconds() * 1000.0

#%%
from datetime import datetime
# 100.000 events
# top -l 10000 -o mem -pid 6739  > memory.txt

lines = []
mem = []
time = []

with open("/content/memory.txt") as file:
    lines = [line.rstrip() for line in file]
    
for i in range(len(lines)):
  if lines[i].startswith("7367"):
    word = lines[i].split(' ')[13]
    word2 = lines[i].split(' ')[4]
    if ((word != '') and (word2 != '')):
      time.append(unix_time_millis(datetime.strptime(word2, "%M:%S.%f")))
      mem.append(int(word[:-2]) * 1e6)
time = np.array(time)

time = time - time[0]
mem = np.array(mem)

#%%
plt.plot(time / 1000, mem / 1e6, c = "black")
plt.xlabel("Time (s)")
plt.ylabel("Allocated memory (MB)")
plt.grid()
plt.title("Allocated memory - 10 milions events simulation")
plt.savefig("memalloc.pdf")

